/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.joedoe;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;

public class App {
    static String DIR = "/media/joe/E/programming/java/code-library/library";

    static Library setup() {
        List<Path> paths = new ArrayList<>();
        try {
            paths = Files.walk(Paths.get(DIR)).filter(Files::isRegularFile).collect(Collectors.toList());
        } catch (IOException e) {
            System.out.println("Opening Directory " + DIR + " failed.");
        }
        Library lib = new Library();
        lib.entries = new Entry[paths.size()];
        int index = 0;
        for (Path path : paths) {
            try (BufferedReader br = new BufferedReader(new FileReader(path.toFile()))) {
                Entry entry = new Entry();
                entry.path = path.toString();
                int count = 0;
                while (count < 3) {
                    String line = br.readLine();
                    if (count == 0) entry.title = line;
                    if (count == 2) entry.src = line;
                    count++;
                }
                lib.entries[index] = entry;
                index++;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        Arrays.sort(lib.entries);
        index = 1;
        for (Entry e : lib.entries) e.index = index++;
        return lib;
    }

    public void printf() {
        String file = DIR + "/streams.txt";

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                System.out.println(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        App app = new App();
//        app.printf();
        Library lib = setup();
        for (Entry e : lib.entries) {
            System.out.println(e);
        }
    }
}
